version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "packages/*"
    schedule:
      interval: "weekly"
    target-branch: "master"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "@types/node"
    groups:
      "minor/patch":
        update-types:
          - "minor"
          - "patch"
      "major":
        update-types:
          - "major"
      "eslint family":
        patterns:
          - "eslint"
          - "eslint-plugin-react"