version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "packages/*"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "@types/node"
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
      dependencies-major:
        update-types:
          - "major"
      dev-dependencies-eslint:
        patterns:
          - "eslint"
          - "neostandard"
          - "@stylistic/*"